# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:ui}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/


spring:
  cloud:
    consul:
      host: consul
      discovery:
        prefer-ip-address: false
